apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: projeks
spec:
  instanceProfile: "projeks_cluster"
  amiFamily: "AL2023"
  amiSelectorTerms:
  - id: ami-02ac2d1c789136a83
  securityGroupSelectorTerms:
  - id: sg-0762e615cb4a6d388
  subnetSelectorTerms:
  - id: subnet-030a49bc013595f68
  - id: subnet-0b8ba96b918244856
  - id: subnet-0d80ff68018a94631
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: projeks
spec:
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m
  template:
    metadata:
      labels:
        workload: "etc"  
    spec:
      requirements:
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values:   
          - t3
          - t3a

        - key: karpenter.k8s.aws/instance-size
          operator: In
          values:
          - medium

        - key: karpenter.sh/capacity-type
          operator: In
          values:
          - "spot"
    
        - key: "topology.kubernetes.io/zone" 
          operator: In
          values:
          - "us-east-1a"
          - "us-east-1b"
          - "us-east-1c"          
          
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: projeks